### ISSUE TITLE
Разработать схему БД приложения

### ISSUE THREAD

**Issue by EvilLord666** [EvilLord666/Cassette#1]
Необходимо разработать схему БД с учетом того, что приложение должно выполнять следующие функции:

1. Подключение к брокерам сообщений: RabbitMq, Apache Kafka , Active Mq
2. Получение списка топиков, создание/удаление топиков
3. Очистка сообщений из очередей
4. Формирование сообщения и возможность отправки его как броадкастом, так и определенному адресату

Для этого в БД необходимо хранить информацию о брокерах и настройках подключения к ним, сообщения (вероятно, необходимо еще хранить и список адресатов). Поскольку сами сообщения могут быть большими (десятки мегабайт), необходимо сохранять их в файловой системе. Также для каждого сообщения необходимо хранить статус. Кроме того одно сообщение можно отправлять разным брокерам, поэтому это также нужно учесть при проектировании схемы.

**Comment by EvilLord666** [comment]
Предлагаю разработать схему БД в Mysql Workbench

**Comment by Drobashique** [comment]
![MQ](https://user-images.githubusercontent.com/65277374/113281853-ca5e9500-92ee-11eb-9135-cf7624c622bd.png)

**Comment by Drobashique** [comment]
[Mq.pdf](https://github.com/EvilLord666/Cassette/files/6243069/Mq.pdf)

**Comment by EvilLord666** [comment]
Согласно описанию: https://github.com/EvilLord666/Cassette/wiki/%D0%9F%D1%80%D0%B5%D0%B4%D0%BC%D0%B5%D1%82%D0%BD%D0%B0%D1%8F-%D0%BE%D0%B1%D0%BB%D0%B0%D1%81%D1%82%D1%8C:-%D0%B8%D0%BD%D1%84%D0%BE%D1%80%D0%BC%D0%B0%D1%86%D0%B8%D0%B8-%D0%BE-%D0%B1%D1%80%D0%BE%D0%BA%D0%B5%D1%80%D0%B0%D1%85,-%D0%BE%D1%87%D0%B5%D1%80%D0%B5%D0%B4%D1%8F%D1%85-%D0%B8-%D1%82%D0%BE%D0%BF%D0%B8%D0%BA%D0%B0%D1%85-(Kafka-%D0%B8-ActiveMq-RabbitMq)

Нам потребуется реализовать следующие таблицы:
- broker_type (не описана в документе, но нужна, чтобы в коде создавать клиент нужного типа)
- broker 
- message

**Comment by Drobashique** [comment]
![MQ](https://user-images.githubusercontent.com/65277374/113676793-86d8a200-96c5-11eb-8ccf-2c1d772a5020.png)
Добавлена таблица с креденшиалами
Связь многие ко многим между сообщениями и брокерами с типом определенного брокера

**Comment by EvilLord666** [comment]
@Drobashique ,
1. Лучше пусть будет таблица не Credentials, а Users/Accounts. длина полей маловата, пусть по 256 символов хранится. login -> username
2.  В broker описанию хватит - 512 символов (NULL) имени - 128 (имя брокера - уникальное) hostname и port лучше заменить одним полем address (т.к. возможно придется записывать и протокол), адрес д.б. строкой до 128 символов
3. В message Адрес будем прикреплять к ообщению т.е. таблица address не нужна. Нужна таблица статуса сообщения (3 поля (id, code, name) у message должна быть ссылка на broker.
4.  broker_type должен быть привязан к broker, а не к message

**Comment by Drobashique** [comment]
![mq1](https://user-images.githubusercontent.com/65277374/113859538-b1058f00-97ad-11eb-95d2-c218d725030a.png)

**Comment by Drobashique** [comment]
![mq1](https://user-images.githubusercontent.com/65277374/113860867-3178bf80-97af-11eb-8fa1-e0a5858064d2.png)

**Comment by EvilLord666** [comment]
@Drobashique, у нас не будет храниться body в таблице, сообщения могут быть большими, они будут лежать на диске
path добавь длину до 300 (хотя она, как правило, 260-300), внутрь message нужно поместить еще поле:
-очередь/топик (строка)

**Comment by Drobashique** [comment]
![mqq](https://user-images.githubusercontent.com/65277374/114004266-2719fc80-9867-11eb-96ef-699c7702fee5.png)

**Comment by EvilLord666** [comment]
Предварительно считаем, что это подходит. Необходимо инициализировать по gitflow от ветки develop создать ветку feature/1_ApplicationSchema (схема формирования имен веток: номер задачи на гитхабе_Красткое описание сути задачи) ив этой ветке создать директорию docs/dbSchema, в которой положить скрипт для создания БД. @Drobashique

**Comment by DPechurkin** [comment]
[menager_brokers.pdf](https://github.com/EvilLord666/Cassette/files/6295438/menager_brokers.pdf)

**Comment by DPechurkin** [comment]
Сделал свою версию модели базы

**Comment by DPechurkin** [comment]
![model](https://user-images.githubusercontent.com/2410789/114374507-24881180-9b9d-11eb-9ca3-c5cf3c779813.png)

**Comment by EvilLord666** [comment]
задача завершена
